version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - github_actions
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - ruby
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - govuk-pay
  - docker
